// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/api/jwt.ts";
import * as $1 from "./routes/api/toot.tsx";
import * as $2 from "./routes/auth/redirect.tsx";
import * as $3 from "./routes/doodle.tsx";
import * as $4 from "./routes/home.tsx";
import * as $5 from "./routes/index.tsx";
import * as $6 from "./routes/login/[name].ts";
import * as $$0 from "./islands/Editor.tsx";
import * as $$1 from "./islands/Gibberish.tsx";
import * as $$2 from "./islands/Home.tsx";
import * as $$3 from "./islands/Login.tsx";
import * as $$4 from "./islands/SaveUserData.tsx";

const manifest = {
  routes: {
    "./routes/api/jwt.ts": $0,
    "./routes/api/toot.tsx": $1,
    "./routes/auth/redirect.tsx": $2,
    "./routes/doodle.tsx": $3,
    "./routes/home.tsx": $4,
    "./routes/index.tsx": $5,
    "./routes/login/[name].ts": $6,
  },
  islands: {
    "./islands/Editor.tsx": $$0,
    "./islands/Gibberish.tsx": $$1,
    "./islands/Home.tsx": $$2,
    "./islands/Login.tsx": $$3,
    "./islands/SaveUserData.tsx": $$4,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
