// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/auth/redirect.tsx";
import * as $1 from "./routes/index.tsx";
import * as $2 from "./routes/login.tsx";
import * as $3 from "./routes/login/[name].ts";
import * as $$0 from "./islands/Login.tsx";
import * as $$1 from "./islands/Welcome.tsx";

const manifest = {
  routes: {
    "./routes/auth/redirect.tsx": $0,
    "./routes/index.tsx": $1,
    "./routes/login.tsx": $2,
    "./routes/login/[name].ts": $3,
  },
  islands: {
    "./islands/Login.tsx": $$0,
    "./islands/Welcome.tsx": $$1,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
